version: "3.4"

services:
  api:
    container_name: jobcontroll
    image: jobcontroll
    environment:
      - PORT=5000
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - job_controll

networks:
  time_track:
    driver: bridge
